// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallApp(arg1:string):Promise<void>;

export function IsInstalled(arg1:string):Promise<boolean>;
